<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ConstantsGen</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Conscia.Domain\Conscia.Domain.csproj" />
    <ProjectReference Include="..\..\src\Conscia.Application\Conscia.Application.csproj" />
  </ItemGroup>
</Project>
