/// Flutter icons Conscia
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Conscia
///      fonts:
///       - asset: fonts/Conscia.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Conscia {
  Conscia._();

  static const _kFontFam = 'Conscia';
  static const String? _kFontPkg = null;

  static const IconData alert = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bills = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bonus = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData debt = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dining = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData family = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entertainment = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fee = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData freelance = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gaming = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData groceries = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData income = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insight = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData investment = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monk = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reflect = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recurring = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refund = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rental_income = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salary = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData savings = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sprout = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscription = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trail = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfer = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transport = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
